name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'client/**'
      - '.github/workflows/android-build.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package.json

      - name: Install dependencies (client)
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Sync Capacitor (Android)
        run: npx cap sync android

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Android debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mess-management-debug-apk
          path: client/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
